apiVersion: v1
kind: Service
metadata:
  name: {{ include "arksec.cluster.mongodb" . }}
  labels:
{{ include "arksec.labels" . | indent 4 }}
    component.arksec.io/name: cluster-mongodb
spec:
  type: ClusterIP
  ports:
    - port: 27017
      protocol: TCP
      targetPort: 27017
  selector:
{{ include "arksec.selectorLabels" . | indent 4 }}
    component.arksec.io/name: cluster-mongodb
  type: ClusterIP