{{- if and .Values.cluster.enabled .Values.cluster.scanner.enabled (eq .Values.cluster.scanner.version "v2") -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "arksec.cluster.scanner" . }}
  labels:
{{ include "arksec.labels" . | indent 4 }}
    component.arksec.io/name: scanner
data:
  CLAMAV_ADDR: localhost
  CLAMAV_PORT: "3310"
  CLAMAV_MAP_FOLDER: /data
  CLAMAV_DST_FOLDER: /data
  XDG_CACHE_HOME: /scanner_data/
  REDSTONE_LISTEN: localhost:8080
  REDSTONE_TIMEOUT: 600s

{{- end -}}

