apiVersion: {{ include "common.capabilities.deployment.apiVersion" . }}
kind: Deployment
metadata:
  name: {{ include "arksec.cluster.scanner" . }}
  labels:
{{ include "arksec.labels" . | indent 4 }}
    component.arksec.io/name: scanner
spec:
  replicas: {{ .Values.scanner.replicas }}
  selector:
    matchLabels:
{{ include "arksec.selectorLabels" . | indent 6 }}
      component.arksec.io/name: scanner
  template:
    metadata:
      labels:
{{ include "arksec.labels" . | indent 8 }}
        component.arksec.io/name: scanner
    spec:
      initContainers:
      - name: copy-vuln-data
        image: {{ include "arksec.cluster.scanner.init.image" . }}
        imagePullPolicy: {{ .Values.global.imagePullPolicy }}
        command:
          - /bin/sh
          - -c
        args:
          - "cp -r /data/trivy/* /trivy/"
        volumeMounts:
          - name: trivy-data
            mountPath: /trivy
      - name: copy-av-data
        image: {{ include "arksec.cluster.scanner.init.image" . }}
        imagePullPolicy: {{ .Values.global.imagePullPolicy }}
        command:
        - /bin/sh
        - -c
        - |
          cp -r /data/clamav/* /clamav/
          chmod -R 755 /clamav/
        volumeMounts:
        - name: clamav-data
          mountPath: /clamav
{{ include "common.waitress.container" . | indent 6 }}
      containers:
      - name: engine
        image: {{ include "arksec.cluster.scanner.engine.image" . }}
        imagePullPolicy: {{ .Values.global.imagePullPolicy }}
        command:
        - "/httpscanner"
        args:
        - "--http-listen=:7777"
        envFrom:
        - configMapRef:
            name: {{ include "arksec.cluster.scanner" . }}
        - configMapRef:
            name: {{ include "arksec.cluster" . }}-endpoints
        - configMapRef:
            name: {{ include "arksec.cluster" . }}-common
        volumeMounts:
        - name: shared-data
          mountPath: /data
        {{- with .Values.scanner.engine.resources }}
        resources:
{{ toYaml . | indent 10 }}
        {{- end }}
      - name: server
        image: {{ include "arksec.cluster.scanner.server.image" . }}
        imagePullPolicy: {{ .Values.global.imagePullPolicy }}
        command:
        - "scanner"
        args:
        - "s"
        envFrom:
        - configMapRef:
            name: {{ include "arksec.cluster.scanner" . }}
        - configMapRef:
            name: {{ include "arksec.cluster" . }}-endpoints
        volumeMounts:
        - name: trivy-data
          mountPath: /scanner_data/trivy/
        {{- with .Values.scanner.server.resources }}
        resources:
{{ toYaml . | indent 10 }}
        {{- end }}
      - name: clamav
        image: {{ include "arksec.cluster.scanner.clamav.image" . }}
        imagePullPolicy: {{ .Values.global.imagePullPolicy }}
        envFrom:
        - configMapRef:
            name: {{ include "arksec.cluster.scanner" . }}
        - configMapRef:
            name: {{ include "arksec.cluster" . }}-endpoints
        volumeMounts:
        - name: shared-data
          mountPath: /data
        - name: clamav-data
          mountPath: /var/lib/clamav/
        {{- with .Values.scanner.clamav.resources }}
        resources:
{{ toYaml . | indent 10 }}
        {{- end }}
      volumes:
      - emptyDir: {}
        name: shared-data
      - emptyDir: {}
        name: trivy-data
      - emptyDir: {}
        name: clamav-data
      {{- with .Values.scanner.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
      {{- end -}}
