apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "arksec.cluster.scanner" . }}
  labels:
{{ include "arksec.labels" . | indent 4 }}
    component.arksec.io/name: scanner
data:
  CLAMAV_ADDR: 127.0.0.1
  CLAMAV_PORT: "3310"
  CLAMAV_MAP_FOLDER: /data
  CLAMAV_DST_FOLDER: /data
  XDG_CACHE_HOME: /scanner_data/
  REDSTONE_LISTEN: localhost:8080
  REDSTONE_TIMEOUT: 600s
