{{- if .Values.cluster.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "arksec.cluster" . }}-common
  labels:
{{ include "arksec.labels" . | indent 4 }}
data:
  CLUSTER_NAME: "{{ .Values.cluster.name }}"
  PLATFORM: "{{ include "common.platform.name" . }}"
  PLATFORM_VERSION: "{{ include "common.platform.version" . }}"
  {{- if eq "openshift" (include "common.platform.name" . ) }}
  CONTAINER_RUNTIME: "crio"
  {{- else }}
  CONTAINER_RUNTIME: "{{ .Values.cluster.cri.type }}"
  {{- end }}
  NETWORK_RUNTIME: "{{ .Values.cluster.cni.type }}"
  NETWORK_RUNTIME_VERSION: "{{ .Values.cluster.cni.apiVersion }}"

  DOCKER_API_VERSION: "{{ .Values.cluster.cri.apiVersion }}"

  CONFIG_FOLDER: /arksec/config/
{{- end -}}