{{- if and .Values.cluster.enabled .Values.cluster.migrate.enabled -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "arksec.cluster.init" . }}-mongodb
  labels:
{{ include "arksec.labels" . | indent 4 }}
    component.arksec.io/name: init-mongodb
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "30"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  backoffLimit: 5
  ttlSecondsAfterFinished: 10000
  activeDeadlineSeconds: 1000
  template:
    metadata:
      name: {{ include "arksec.cluster.init" . }}-mongodb
      labels:
{{ include "arksec.labels" . | indent 8 }}
        component.arksec.io/name: init-mongodb
    spec:
      {{- if .Values.common.waitress.enabled }}
      initContainers:
{{ include "common.waitress.container" . | indent 6 }}
      {{- end }}
      containers:
      - name: migrate
        image: {{ include "arksec.cluster.migrate.image" . }}
        imagePullPolicy: {{ .Values.global.imagePullPolicy }}
        command:
        - /migrate-backend
        args:
        - --mongo-endpoint={{ include "arksec.cluster.mongodb.host" . }}:{{ include "arksec.cluster.mongodb.port" . }}
        - --mongo-password={{ include "arksec.cluster.mongodb.rawPassword" . }}
        - --mongo-username={{ include "arksec.cluster.mongodb.username" . }}
        {{- if .Values.cluster.migrate.resources }}
        resources:
{{ toYaml .Values.cluster.migrate.resources | indent 10 }}
        {{- end }}
      restartPolicy: Never
      imagePullSecrets: 
{{ include "arksec.global.imagePullSecret" . | indent 8 }}
      {{- with .Values.cluster.migrate.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
      {{- end -}}
{{- end -}}