apiVersion: v1
metadata:
  name: {{ include "arksec.default.dockerconfigjson" . }}
  labels:
{{ include "arksec.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "0"
kind: Secret
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "arksec.dockerconfigjson" . }}
