apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "arksec.cluster" . }}-common
  labels:
{{ include "arksec.labels" . | indent 4 }}
data:
  PLATFORM: "{{ include "common.platform.name" . }}"
  PLATFORM_VERSION: "{{ include "common.platform.version" . }}"
  CONFIG_FOLDER: /arksec/config/
  CLUSTER_NAME: "default"
  PLATFORM: "kubernetes"
  PLATFORM_VERSION: "{{ include "common.platform.version" . }}"
  CONTAINER_RUNTIME: "docker"
  DOCKER_API_VERSION: "1.40"
  CONFIG_FOLDER: /arksec/config/